INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (1, 'VALENTINA ULLOA GATICA', 'CHILLAN', 'Soc Ortiz y Toloza Spa', 'ASISTENTE RX', '2020-10-14');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (1, 1, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (2, 'JAVIERA SANHUEZA NAVARRETE', 'CHILLAN', 'Soc Ortiz y Toloza Spa', 'ENCARGADA SUCURSAL | ASISTENTE RX', '2020-08-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (2, 2, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (3, 'DANIELA SOTO ULLOA', 'CHILLAN', 'Soc Ortiz y Toloza Spa', 'ASISTENTE RX', '2020-08-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (3, 3, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (4, 'FERNANDA CASTILLO FLORES', 'CHILLAN', 'Soc Ortiz y Toloza Spa', 'ASISTENTE RX', '2022-02-15');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (4, 4, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (5, 'YERALDINE CARRASCO CISTERNAS', 'CHILLAN', 'Soc Ortiz y Toloza Spa', 'ASISTENTE RX', '2022-06-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (5, 5, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (6, 'BRIGITTE CORREA PINILLA', 'CHILLAN', 'Soc Ortiz y Toloza Spa', 'ASISTENTE RX', '2022-02-15');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (6, 6, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (7, 'TAMARA SANHUEZA TAPIA', 'CHILLAN', 'Soc Ortiz y Toloza Spa', 'CAJERA', '2022-06-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (7, 7, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (8, 'ERENGART SILVA', 'CHILLAN', 'Soc Ortiz y Toloza Spa', 'ASISTENTE ADMINISTRATIVO', '2022-05-23');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (8, 8, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (9, 'EIMY GAMONAL FUENTEALBA', 'LAS RASTRAS | TALCA', 'Soc Ortiz y Toloza Spa', 'ENCARGADA SUCURSAL | ASISTENTE RX', '2020-08-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (9, 9, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (10, 'IRANI ROJAS ROJAS', 'LAS RASTRAS | TALCA', 'Soc Ortiz y Toloza Spa', 'CAJERA', '2022-09-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (10, 10, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (11, 'KREILYS AVILA BRACHO', 'LAS RASTRAS | TALCA', 'Soc Ortiz y Toloza Spa', 'ASISTENTE RX', '2023-02-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (11, 11, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (12, 'KARINA FAUNDEZ VASQUEZ', 'TALCA | CENTRO', 'Soc Ortiz y Toloza Spa', 'ENCARGADA SUCURSAL | ASISTENTE RX', '2018-05-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (12, 12, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (13, 'JENNIFER RAMOS GONZALEZ', 'TALCA | CENTRO', 'Soc Ortiz y Toloza Spa', 'ASISTENTE RX', '2023-01-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (13, 13, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (14, 'JAEL ESPINOZA PINEDO', 'TALCA | CENTRO', 'Soc Ortiz y Toloza Spa', 'ASISTENTE RX', '2022-10-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (14, 14, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (15, 'NATALIA LEIVA ROJAS', 'TALCA | CENTRO', 'Soc Ortiz y Toloza Spa', 'ASISTENTE RX', '2021-10-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (15, 15, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (16, 'VANESSA CONEJEROS MARTINEZ', 'TALCA | CENTRO', 'Soc Ortiz y Toloza Spa', 'ASISTENTE RX', '2021-10-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (16, 16, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (17, 'SARA SANCHEZ CANALES', 'TALCA | CENTRO', 'Soc Ortiz y Toloza Spa', 'CAJERA', '2020-10-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (17, 17, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (18, 'ELIZABETH GONZALEZ MELENDEZ', 'TALCA | CENTRO', 'Soc Ortiz y Toloza Spa', 'CAJERA', '2021-08-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (18, 18, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (19, 'ANTONIA AVILA', 'TALCA | CENTRO', 'Soc Ortiz y Toloza Spa', 'RECEPCIONISTA', '2022-07-11');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (19, 19, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (20, 'CONCEPCION CANTOS GUTIERREZ', 'TALCA | CENTRO', 'Soc Ortiz y Toloza Spa', 'SECRETARIA', '2019-03-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (20, 20, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (21, 'VALERIA QUIJON', 'TALCA | CENTRO', 'Soc Ortiz y Toloza Spa', 'ASISTENTE ADMINISTRATIVO', '2022-08-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (21, 21, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (22, 'SOLANGE FUENTES CALLOFA', 'TALCA | CENTRO', 'Soc Ortiz y Toloza Spa', 'ADMINISTRADORA', '2021-11-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (22, 22, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (23, 'FRANCISCO VILCHES VALENZUELA', 'TALCA | CENTRO', 'Soc Ortiz y Toloza Spa', 'ASISTENTE DE GERENCIA', '2021-08-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (23, 23, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (24, 'JOHANA CONTRERAS', 'TALCA | CENTRO', 'Comercial FC Spa', 'DESARROLLADOR Y SOPORTE INFORMATICO', '2022-06-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (24, 24, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (25, 'JUAN BRICEÑO', 'TALCA | CENTRO', 'Comercial FC Spa', 'DESARROLLADOR Y SOPORTE INFORMATICO', '2022-08-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (25, 25, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (26, 'DANIEL HERNANDEZ', 'TALCA | CENTRO', 'Comercial FC Spa', 'DESARROLLADOR Y SOPORTE INFORMATICO', '2022-05-02');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (26, 26, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (27, 'MARLENE OLAVE', 'TALCA | CENTRO', 'Comercial FC Spa', 'REALIZADORA MULTIMEDIA', '2022-10-06');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (27, 27, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (28, 'CRISTOBAL MUÑOZ', 'TALCA | CENTRO', 'Comercial FC Spa', 'REALIZADOR MULTIMEDIA', '2023-04-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (28, 28, 5, '2023-05-01');
INSERT INTO empleado (idempleado, nombre, sucursal, empresa, cargo, fecha_ingreso)                     VALUES (29, 'DANILO DUARTE BUENO', 'TALCA | CENTRO', 'Comercial FC Spa', 'DISEÑADOR GRAFICO', '2023-04-01');
INSERT INTO dias_admin(iddias_admin, empleado_idempleado, cantidad_dias, anio)                     VALUES (29, 29, 5, '2023-05-01');
