
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (40,'PRECIO NORMAL',4000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (40,'PRECIO CONVENIO',3500,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (40,'REIMPRESION',1500,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (41,'PRECIO NORMAL',4000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (41,'PRECIO CONVENIO',3500,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (41,'REIMPRESION',1500,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (42,'PRECIO NORMAL',16000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (42,'PRECIO CONVENIO',14000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (42,'REIMPRESION',6000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (43,'PRECIO NORMAL',36000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (43,'PRECIO CONVENIO',33000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (43,'REIMPRESION',12000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (44,'PRECIO NORMAL',12000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (44,'PRECIO CONVENIO',10500,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (44,'REIMPRESION',4500,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (45,'PRECIO NORMAL',22000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (45,'PRECIO CONVENIO',20000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (45,'REIMPRESION',6000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (46,'PRECIO NORMAL',18000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (46,'PRECIO CONVENIO',16000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (46,'REIMPRESION',6000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (47,'PRECIO NORMAL',18000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (47,'PRECIO CONVENIO',16000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (47,'REIMPRESION',6000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (48,'PRECIO NORMAL',15000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (48,'PRECIO CONVENIO',12000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (48,'REIMPRESION',6000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (49,'PRECIO NORMAL',23000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (49,'PRECIO CONVENIO',20000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (49,'REIMPRESION',6000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (50,'PRECIO NORMAL',23000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (50,'PRECIO CONVENIO',20000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (50,'REIMPRESION',60000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (51,'PRECIO NORMAL',48000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (51,'PRECIO CONVENIO',46000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (51,'DR. CARLOS GONZALEZ, ARMANDO ESPINOZA, GONZALO MUÑOZ, ALFREDO ESPINOZA',30000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (51,'REIMPRESION',20000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (52,'PRECIO NORMAL',48000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (52,'PRECIO CONVENIO',46000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (52,'DR. CARLOS GONZALEZ, ARMANDO ESPINOZA, GONZALO MUÑOZ, ALFREDO ESPINOZA',30000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (52,'REIMPRESION',20000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (53,'PRECIO NORMAL',80000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (53,'PRECIO CONVENIO',69500,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (53,'DR. CARLOS GONZALEZ, ARMANDO ESPINOZA, GONZALO MUÑOZ, ALFREDO ESPINOZA',40000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (53,'REIMPRESION',30000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (54,'PRECIO NORMAL',38000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (54,'PRECIO CONVENIO',36000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (54,'DR. CARLOS GONZALEZ, ARMANDO ESPINOZA, GONZALO MUÑOZ, ALFREDO ESPINOZA',25000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (54,'REIMPRESION',15000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (55,'PRECIO NORMAL',48000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (55,'PRECIO CONVENIO',46000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (55,'DR. CARLOS GONZALEZ, ARMANDO ESPINOZA, GONZALO MUÑOZ, ALFREDO ESPINOZA',30000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (55,'REIMPRESION',20000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (56,'PRECIO NORMAL',60000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (56,'PRECIO CONVENIO',50000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (56,'DR. CARLOS GONZALEZ, ARMANDO ESPINOZA, GONZALO MUÑOZ, ALFREDO ESPINOZA',40000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (56,'REIMPRESION',20000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (57,'PRECIO NORMAL',60000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (57,'PRECIO CONVENIO',50000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (57,'DR. CARLOS GONZALEZ, ARMANDO ESPINOZA, GONZALO MUÑOZ, ALFREDO ESPINOZA',40000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (57,'REIMPRESION',20000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (58,'PRECIO NORMAL',80000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (58,'PRECIO CONVENIO',69500,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (58,'DR. CARLOS GONZALEZ, ARMANDO ESPINOZA, GONZALO MUÑOZ, ALFREDO ESPINOZA',55000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (58,'REIMPRESION',30000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (59,'PRECIO NORMAL',10500,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (59,'PRECIO CONVENIO',9000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (59,'REIMPRESION',6000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (60,'PRECIO NORMAL',10500,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (60,'PRECIO CONVENIO',9000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (60,'REIMPRESION',6000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (61,'PRECIO NORMAL',10500,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (61,'PRECIO CONVENIO',9000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (61,'REIMPRESION',6000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (62,'PRECIO NORMAL',10500,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (62,'PRECIO CONVENIO',9000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (62,'REIMPRESION',6000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (63,'PRECIO NORMAL',10500,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (63,'PRECIO CONVENIO',9000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (63,'REIMPRESION',6000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (64,'PRECIO NORMAL',21000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (64,'PRECIO CONVENIO',18500,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (64,'REIMPRESION',8000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (85,'PRECIO NORMAL',25000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (86,'PRECIO NORMAL',25000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (87,'PRECIO NORMAL',10000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (88,'PRECIO NORMAL',10000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (89,'PRECIO NORMAL',15000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (90,'PRECIO NORMAL',15000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (91,'PRECIO NORMAL',15000,5);
INSERT INTO nombre_descuento (prestaciones_idprestaciones,tipo_descuento,precio, ubicacion_empresa_idubicacion_empresa)             VALUES (92,'PRECIO NORMAL',25000,5);
