INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (40, 'PRECIO NORMAL', 4000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (40, 'PRECIO CONVENIO', 3500, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (40, 'REIMPRESION', 1500, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (41, 'PRECIO NORMAL', 4000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (41, 'PRECIO CONVENIO', 3500, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (41, 'REIMPRESION', 1500, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (42, 'PRECIO NORMAL', 16000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (42, 'PRECIO CONVENIO', 14000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (42, 'REIMPRESION', 6000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (43, 'PRECIO NORMAL', 36000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (43, 'PRECIO CONVENIO', 33000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (43, 'REIMPRESION', 12000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (44, 'PRECIO NORMAL', 12000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (44, 'PRECIO CONVENIO', 10500, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (44, 'REIMPRESION', 4500, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (45, 'PRECIO NORMAL', 22000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (45, 'PRECIO CONVENIO', 20000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (45, 'REIMPRESION', 6000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (46, 'PRECIO NORMAL', 18000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (46, 'PRECIO CONVENIO', 16000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (46, 'REIMPRESION', 6000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (47, 'PRECIO NORMAL', 18000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (47, 'PRECIO CONVENIO', 16000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (47, 'REIMPRESION', 6000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (48, 'PRECIO NORMAL', 15000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (48, 'PRECIO CONVENIO', 12000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (48, 'REIMPRESION', 6000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (49, 'PRECIO NORMAL', 23000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (49, 'PRECIO CONVENIO', 20000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (49, 'REIMPRESION', 6000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (50, 'PRECIO NORMAL', 23000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (50, 'PRECIO CONVENIO', 20000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (50, 'REIMPRESION', 60000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (51, 'PRECIO NORMAL', 48000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (51, 'PRECIO CONVENIO', 46000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (51, 'REIMPRESION', 20000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (52, 'PRECIO NORMAL', 48000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (52, 'PRECIO CONVENIO', 46000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (52, 'REIMPRESION', 20000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (53, 'PRECIO NORMAL', 80000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (53, 'PRECIO CONVENIO', 69500, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (53, 'REIMPRESION', 30000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (54, 'PRECIO NORMAL', 38000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (54, 'PRECIO CONVENIO', 36000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (54, 'REIMPRESION', 15000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (55, 'PRECIO NORMAL', 48000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (55, 'PRECIO CONVENIO', 46000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (55, 'REIMPRESION', 20000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (56, 'PRECIO NORMAL', 60000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (56, 'PRECIO CONVENIO', 50000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (56, 'REIMPRESION', 20000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (57, 'PRECIO NORMAL', 60000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (57, 'PRECIO CONVENIO', 50000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (57, 'REIMPRESION', 20000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (58, 'PRECIO NORMAL', 80000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (58, 'PRECIO CONVENIO', 69500, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (58, 'REIMPRESION', 30000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (59, 'PRECIO NORMAL', 10500, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (59, 'PRECIO CONVENIO', 9000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (59, 'REIMPRESION', 6000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (60, 'PRECIO NORMAL', 10500, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (60, 'PRECIO CONVENIO', 9000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (60, 'REIMPRESION', 6000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (61, 'PRECIO NORMAL', 10500, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (61, 'PRECIO CONVENIO', 9000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (61, 'REIMPRESION', 6000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (62, 'PRECIO NORMAL', 10500, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (62, 'PRECIO CONVENIO', 9000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (62, 'REIMPRESION', 6000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (63, 'PRECIO NORMAL', 10500, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (63, 'PRECIO CONVENIO', 9000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (63, 'REIMPRESION', 6000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (64, 'PRECIO NORMAL', 21000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (64, 'PRECIO CONVENIO', 18500, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (64, 'REIMPRESION', 8000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (87, 'PRECIO NORMAL', 10000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (88, 'PRECIO NORMAL', 10000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (89, 'PRECIO NORMAL', 15000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (85, 'PRECIO NORMAL', 27000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (86, 'PRECIO NORMAL', 27000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (92, 'PRECIO NORMAL', 27000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (51, 'SOLO CD O SOLO DICOM - T', 30000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (52, 'SOLO CD O SOLO DICOM - T', 30000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (93, 'PRECIO NORMAL', 60000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (96, 'PRECIO NORMAL', 60000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (91, 'PRECIO NORMAL', 17000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (90, 'PRECIO NORMAL', 17000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (39, 'PRECIO NORMAL', 45000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (94, 'PRECIO NORMAL', 160000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (95, 'PRECIO NORMAL', 40000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (97, 'PRECIO NORMAL', 10500, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (97, 'PRECIO CONVENIO', 9000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (84, 'PRECIO CONVENIO', 9000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (84, 'PRECIO NORMAL', 10500, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (97, 'REIMPRESION', 6000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (84, 'REIMPRESION', 6000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (98, 'PRECIO NORMAL', 25000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (51, 'SOLO INFORME CBCT', 16000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (52, 'SOLO INFORME CBCT', 16000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (53, 'SOLO INFORME CBCT', 29500, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (54, 'SOLO INFORME CBCT', 11000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (55, 'SOLO INFORME CBCT', 16000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (56, 'SOLO INFORME CBCT', 10000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (57, 'SOLO INFORME CBCT', 10000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (58, 'SOLO INFORME CBCT', 14500, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (53, 'SOLO CD O SOLO DICOM - T', 40000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (54, 'SOLO CD O SOLO DICOM - T', 25000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (55, 'SOLO CD O SOLO DICOM - T', 30000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (56, 'SOLO CD O SOLO DICOM - T', 40000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (57, 'SOLO CD O SOLO DICOM - T', 40000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (58, 'SOLO CD O SOLO DICOM - T', 55000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (99, 'PRECIO NORMAL', 4000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (99, 'PRECIO CONVENIO', 3500, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (99, 'REIMPRESION', 1500, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (100, 'PRECIO NORMAL', 95000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (100, 'PRECIO CONVENIO', 80000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (41, 'CONV DIPRECA FFAA', 3000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (40, 'CONV DIPRECA FFAA', 3000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (43, 'CONV DIPRECA FFAA', 30000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (45, 'CONV DIPRECA FFAA', 18000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (42, 'CONV DIPRECA FFAA', 12000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (46, 'CONV DIPRECA FFAA', 15000, 7);
INSERT INTO nombre_descuento (prestaciones_idprestaciones, tipo_descuento, precio, ubicacion_empresa_idubicacion_empresa) VALUES (100, 'SOLO CD O SOLO DICOM - T', 50000, 7);