UPDATE empleado SET email = 'vulloagatica@gmail.com' WHERE nombre = 'VALENTINA ULLOA GATICA';
UPDATE empleado SET email = 'javierasanhueza@gmail.com ' WHERE nombre = 'JAVIERA SANHUEZA NAVARRETE';
UPDATE empleado SET email = 'sotodaniela@live.com ' WHERE nombre = 'DANIELA SOTO ULLOA';
UPDATE empleado SET email = 'CASTILLOF261@gmail.com ' WHERE nombre = 'FERNANDA CASTILLO FLORES';
UPDATE empleado SET email = 'yeraldinecarrasco@gmail.com ' WHERE nombre = 'YERALDINE CARRASCO CISTERNAS';
UPDATE empleado SET email = 'bcorrea578@gmail.com' WHERE nombre = 'BRIGITTE CORREA PINILLA';
UPDATE empleado SET email = 'tsanhueza1816@gmail.com' WHERE nombre = 'TAMARA SANHUEZA TAPIA';
UPDATE empleado SET email = 'ERENGART.TJ@gmail.com ' WHERE nombre = 'ERENGART SILVA';
UPDATE empleado SET email = 'eimy.gamonaal@hotmail.com ' WHERE nombre = 'EIMY GAMONAL FUENTEALBA';
UPDATE empleado SET email = 'iranidelpilarr@hotmail.com ' WHERE nombre = 'IRANI ROJAS ROJAS';
UPDATE empleado SET email = 'avilakreilys@gmail.com' WHERE nombre = 'KREILYS AVILA BRACHO';
UPDATE empleado SET email = 'karina.faundez91@gmail.com ' WHERE nombre = 'KARINA FAUNDEZ VASQUEZ';
UPDATE empleado SET email = 'jennifer.bramosg@gmail.com' WHERE nombre = 'JENNIFER RAMOS GONZALEZ';
UPDATE empleado SET email = 'Jael.Espinoza.Ad.insuco@gmail.com ' WHERE nombre = 'JAEL ESPINOZA PINEDO';
UPDATE empleado SET email = 'natalia_leivarojas@hotmail.com' WHERE nombre = 'NATALIA LEIVA ROJAS';
UPDATE empleado SET email = 'vanessa.conejeros.26@gmail.com ' WHERE nombre = 'VANESSA CONEJEROS MARTINEZ';
UPDATE empleado SET email = 'sary34@gmail.com ' WHERE nombre = 'SARA SANCHEZ CANALES';
UPDATE empleado SET email = 'ely_cony15@hotmail.com' WHERE nombre = 'ELIZABETH GONZALEZ MELENDEZ';
UPDATE empleado SET email = 'antoavilavasquez@gmail.com' WHERE nombre = 'ANTONIA AVILA';
UPDATE empleado SET email = 'concecantos@gmail.com ' WHERE nombre = 'CONCEPCION CANTOS GUTIERREZ';
UPDATE empleado SET email = 'valery2683@gmail.com ' WHERE nombre = 'VALERIA QUIJON';
UPDATE empleado SET email = 'sfcallofa@gmail.com ' WHERE nombre = 'SOLANGE FUENTES CALLOFA';
UPDATE empleado SET email = 'francisco.ignaciovilches@gmail.com ' WHERE nombre = 'FRANCISCO VILCHES VALENZUELA';
UPDATE empleado SET email = 'johakrys1109@gmail.com ' WHERE nombre = 'JOHANNA CONTRERAS';
UPDATE empleado SET email = 'juanfranbr99@gmail.com ' WHERE nombre = 'JUAN BRICEÑO';
UPDATE empleado SET email = 'daniher02@gmail.com ' WHERE nombre = 'DANIEL HERNANDEZ';
UPDATE empleado SET email = 'marlenolave2008@gmail.com' WHERE nombre = 'MARLENE OLAVE';
UPDATE empleado SET email = 'SIN EMAIL' WHERE nombre = 'CRISTOBAL MUÑOZ';
UPDATE empleado SET email = 'daniloduartebueno@gmail.com' WHERE nombre = 'DANILO DUARTE BUENO';
