
UPDATE prestaciones SET codigo = '037' WHERE nombre_prestacion = 'PACK OASIS PANO/TELE PERFIL/BITEWING/ 1 ANALISIS/ FOTOS CLINICAS';
UPDATE prestaciones SET codigo = '038' WHERE nombre_prestacion = 'PACK PANO/TELE PERFIL/BITEWING/ 1 ANALISIS';
UPDATE prestaciones SET codigo = '039' WHERE nombre_prestacion = 'PACK OASIS- PANO/TELE PERFIL/BITEWING/ 1 ANALISIS/';
UPDATE prestaciones SET codigo = '040' WHERE nombre_prestacion = 'PACK CLINICA SAN FRANCISCO (PANORAMICA-TELERADIOGRAFIA-BITE WING)';
UPDATE prestaciones SET codigo = '041' WHERE nombre_prestacion = 'PACK ORALCENTER (PANORAMICA-TELERADIOGRAFIA-2ANALISIS)';
UPDATE prestaciones SET codigo = '042' WHERE nombre_prestacion = 'CONE BEAM MAX SUP CONVENIO ORALCENTER Y UNO SALUD-FULLMEDS';
UPDATE prestaciones SET codigo = '043' WHERE nombre_prestacion = 'CONE BEAM MAX INF CONVENIO ORALCENTER Y UNO SALUD- FULLMED';
UPDATE prestaciones SET codigo = '044' WHERE nombre_prestacion = 'CONE BEAM BIMAXILAR CONVENIO ORAL CENTER Y UNO SALUD- FULLMEDS';
UPDATE prestaciones SET codigo = '045' WHERE nombre_prestacion = 'PACK PDI (PANORAMICA-BITE WING)';
UPDATE prestaciones SET codigo = '046' WHERE nombre_prestacion = 'PACK PERFECT DENTAL PANO/TELE PERFIL/BITEWING/ 1 ANALISIS/ FOTOS CLINICAS';
